<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * analisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class analisisRepository extends EntityRepository {

    public function findAnalisis($dato, $criterio) {
        $resultado = null;
        if ($criterio == "id") {
            $resultado = $this->findAnalisisPorNumero($dato);
        };
        if ($criterio == "fecha") {
            $resultado = $this->findAnalisisPorFecha($dato);
        };
        if ($criterio == "donacion") {
            $resultado = $this->findAnalisisPorDonacion($dato);
        }
        return $resultado;
    }

    public function findAnalisisPorNumero($id) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Analisis d where d.id like :id";

        $query = $em->createQuery($dql);
        $query->setParameter('id', '%' . $id . '%');

        $analisis = $query->getResult();
        return $analisis;
    }

    public function findAnalisisPorFecha($fecha) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Analisis d where d.fechanalisis = :fechanalisis";

        $query = $em->createQuery($dql);
        $query->setParameter('fechanalisis', $fecha);

        $analisis = $query->getResult();
        return $analisis;
    }

    public function findAnalisisPorDonacion($nro) {
        $em = $this->getEntityManager();
        if ($nro == '') {
            $dql = "select a from HSYSMainBundle:Analisis a";
            
            $query = $em->createQuery($dql);
        } else {
            $dql = "select a from HSYSMainBundle:Analisis a, HSYSMainBundle:Donacion d where d.numdedonacion = :numdon and d.id = a.Donacion";

            $query = $em->createQuery($dql);
            $query->setParameter('numdon', $nro);
        }

        $analisis = $query->getResult();
        return $analisis;
    }

}
