<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonacionRepository extends EntityRepository
{
    public function findDonacionNumero($numero) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Donacion d where d.id like :numero";

        $query = $em->createQuery($dql);
        $query->setParameter('id', '%' . $numero . '%');

        $donaciones = $query->getResult();
        return $donaciones;
    }
}