<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonanteRepository extends EntityRepository {

    public function findDonante($dato, $criterio){
        $resultado;
        if ($criterio == "dni"){
            $resultado = $this->findDonantePorDNI($dato);
        };
        if ($criterio == "id") {
            $resultado = $this->findDonantePorNumero($dato);
        };
        if ($criterio == "nomapp") {
            $resultado = $this->findDonantePorNomApp($dato);
        };
        
        return $resultado;
}
    
    public function findDonantePorDNI($dni) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Donante d where d.dni like :dni";

        $query = $em->createQuery($dql);
        $query->setParameter('dni', $dni);
        
        $donantes = $query->getResult();
        return $donantes;
    }
    
    public function findDonantePorNumero($id) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Donante d where d.id like :id";

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);
        
        $donantes = $query->getResult();
        return $donantes;
    }
    
        public function findDonantePorNomApp($nomapp) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Donante d where d.nomapp like :nomapp";

        $query = $em->createQuery($dql);
        $query->setParameter('nomapp', $nomapp);
        
        $donantes = $query->getResult();
        return $donantes;
    }
}
