<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonanteRepository extends EntityRepository {

    public function findDonante($dato, $criterio){
        $resultado= null;
        if ($criterio == "dni"){
            $resultado = $this->findDonantePorDNI($dato,'D');
        };
        if ($criterio == "pasaporte"){
            $resultado = $this->findDonantePorDNI($dato,'P');
        };
        if ($criterio == "civica"){
            $resultado = $this->findDonantePorDNI($dato,'C');
        };
        if ($criterio == "enrolamiento"){
            $resultado = $this->findDonantePorDNI($dato,'E');
        };
        if ($criterio == "id") {
            $resultado = $this->findDonantePorNumero($dato);
        };
        if ($criterio == "nomapp") {
            $resultado = $this->findDonantePorNomApp($dato);
        };
        
        return $resultado;
}
    
    public function findDonantePorDNI($dni,$tipo) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Donante d where d.dni like :dni and d.baja = false";

        $query = $em->createQuery($dql);
        $query->setParameter('dni', '%'.$tipo.$dni.'%');
        
        $donantes = $query->getResult();
        return $donantes;
    }
    
    public function findDonantePorNumero($id) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Donante d where d.id like :id and d.baja = false";

        $query = $em->createQuery($dql);
        $query->setParameter('id', '%'.$id.'%');
        
        $donantes = $query->getResult();
        return $donantes;
    }
    //UPPER(u.name)
        public function findDonantePorNomApp($nomapp) {
        $em = $this->getEntityManager();
        $dql = "select d from HSYSMainBundle:Donante d where d.nomapp like :nomapp and d.baja=false";

        $query = $em->createQuery($dql);
        $query->setParameter('nomapp', '%'.$nomapp.'%');
        
        $donantes = $query->getResult();
        return $donantes;
    }
    
        public function generarDatosInformeVoluntario() {
        $em = $this->getEntityManager();
        $dql = "select d.factorsang as factor, count(d.id) as cant from HSYSMainBundle:Donante d where d.donantevoluntario=true and d.baja=false group by d.factorsang";

        $query = $em->createQuery($dql);
        
        $donantes = $query->getResult();
        return $donantes;
    }
}
