<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonanteRepository extends EntityRepository {

    public function findDonante($dato, $criterio){
        if ($criterio == "dni"){
            $resultado = findDonanteporDNI($dato);
        }elseif ($criterio == "id") {
            $resultado = findDonanteporDNI($dato);
        }elseif ($criterio == "nomapp") {
            $resultado = findDonanteporDNI($dato);
        }
        
        return $resultado;
}
    
    public function findDonantePorDNI($dni) {
        $em = $this->getEntityManager();
        $dql = "select * from HSYSMainBundle:Donate d where d.dni like :dni";

        $query = $em->createQuery($dql);
        $query->setParameter('dni', $dni);
        
        $donantes = $query->getResult();
        return $donantes;
    }
    
    public function findDonantePorNumero($numero) {
        $em = $this->getEntityManager();
        $dql = "select * from HSYSMainBundle:Donate d where d.id like :numero";

        $query = $em->createQuery($dql);
        $query->setParameter('numero', $numero);
        
        $donantes = $query->getResult();
        return $donantes;
    }
    
        public function findDonantePorNomApp($nomapp) {
        $em = $this->getEntityManager();
        $dql = "select * from HSYSMainBundle:Donate d where d.nomapp like :nomapp";

        $query = $em->createQuery($dql);
        $query->setParameter('nomapp', $nomapp);
        
        $donantes = $query->getResult();
        return $donantes;
    }
}
