<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExclusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExclusionRepository extends EntityRepository
{
}
