<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExclusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExclusionRepository extends EntityRepository
{
    public function findExclusionesdelDonante($iddonate) {
        $em = $this->getEntityManager();
        $dql = "select e from HSYSMainBundle:Exclusion e where (e.Donante = :iddonante) ORDER BY e.fechfin DESC";

        $query = $em->createQuery($dql);
        $query->setParameter('iddonante', $iddonate);
        
        $exclusiones= $query->getResult();
        return $exclusiones;
    }
    
        public function findExclusionesActivas($iddonate) {
        $em = $this->getEntityManager();
        $dql = "select e from HSYSMainBundle:Exclusion e where (e.Donante = :iddonante) and ((e.fechfin > CURRENT_DATE() or e.fechfin IS NULL))";

        $query = $em->createQuery($dql);
        $query->setParameter('iddonante', $iddonate);
        
        $exclusiones= $query->getResult();
 
        return $exclusiones;
    }
     
}
