<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExclusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExclusionRepository extends EntityRepository
{
    public function findDonantePorDNI($iddonate) {
        $em = $this->getEntityManager();
        $dql = "select e, te from HSYSMainBundle:Exclusion e, HSYSMainBundle:TipoExclusion te where (e.TipoExclusion = te.id) and (e.donante = :iddonante) ";

        $query = $em->createQuery($dql);
        $query->setParameter('iddonante', $iddonate);
        
        $exclusiones= $query->getResult();
        return $exclusiones;
    }
    
}
