hsys_main_homepage:
  pattern:  /
  defaults: { _controller: HSYSMainBundle:Inicio:index }

#DONANTES
pagina_donante:
  pattern: /donante
  defaults: { _controller: HSYSMainBundle:Donante:index }

alta_donante:
  pattern: /donante/nuevo
  defaults: { _controller: HSYSMainBundle:Donante:nuevo }

confirmacion:
  pattern: /donante/confirmacion/{accion}/{id}
  defaults: { _controller: HSYSMainBundle:Donante:confirmacion }
    
modificar_donante:
  pattern: /donante/modificar/{id}
  defaults: { _controller: HSYSMainBundle:Donante:modificar }
  
excluir_donante:
  pattern: /donante/excluir/{id}
  defaults: { _controller: HSYSMainBundle:Donante:excluir }

excluir_donante_por_donacion:
  pattern: /donante/excluir/{donanteid}/{donacionid}
  defaults: { _controller: HSYSMainBundle:Donante:excluirdonacion }

buscar_donante:
  pattern: /donante/buscar
  defaults: { _controller: HSYSMainBundle:Donante:buscar }

ver_donante:
  pattern: /donante/ver/{id}
  defaults: { _controller: HSYSMainBundle:Donante:ver }

habilitar_donante:
  pattern: /donante/habilitar/{id}
  defaults: { _controller: HSYSMainBundle:Donante:habilitar }

eliminar_donante:
  pattern: /donante/eliminar/{id}
  defaults: { _controller: HSYSMainBundle:Donante:eliminar }

imprimir_donante:
  pattern: /donante/imprimir/{id}
  defaults: { _controller: HSYSMainBundle:Donante:imprimirDonante }

#EXTRACCIONES/DONACION
pagina_donacion:
  pattern: /donacion
  defaults: { _controller: HSYSMainBundle:Donacion:index }  
  
buscar_donacion_numero:
  pattern: /donacion/buscarpornumero
  defaults: { _controller: HSYSMainBundle:Donacion:buscarNumero }
  
buscar_donacion_donante:
  pattern: /donacion/buscarpordonante
  defaults: { _controller: HSYSMainBundle:Donacion:buscarDonante }
  
buscar_donacion_fecha:
  pattern: /donacion/buscarporfecha
  defaults: { _controller: HSYSMainBundle:Donacion:buscarFecha }
  
alta_donacion:
  pattern: /donacion/nueva
  defaults: { _controller: HSYSMainBundle:Donacion:nuevo }

alta_donacion_voluntaria:
  pattern: /donacion/voluntaria
  defaults: { _controller: HSYSMainBundle:Donacion:voluntaria }
  
alta_donacion_voluntaria_donante:
  pattern: /donacion/voluntaria/donante
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaDonante }

alta_donacion_voluntaria_formulario:
  pattern: /donacion/voluntaria/formulario/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaFormulario }

alta_donacion_voluntaria_formulario_guardar:
  pattern: /donacion/voluntaria/guardar/formulario/
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaFormularioGuardar }
  
#alta_donacion_voluntaria_formulario_guardar:
#  pattern: /donacion/voluntaria/guardar/formulario/{numdedonacion}
#  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaFormularioContinuar }
#  
alta_donacion_voluntaria_formulario_terminado:
  pattern: /donacion/voluntaria/terminado/formulario/{numdedonacion}
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaFormularioContinuar }

alta_donacion_voluntaria_confirmar:
  pattern: /donacion/voluntaria/confirmar
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaConfirmar }

alta_donacion_receptor:
  pattern: /donacion/receptor
  defaults: { _controller: HSYSMainBundle:Donacion:receptor }
  
alta_donacion_receptor_donante:
  pattern: /donacion/receptor/donante
  defaults: { _controller: HSYSMainBundle:Donacion:receptorDonante }
  
alta_donacion_receptor_receptor:
  pattern: /donacion/receptor/{don}/receptor
  defaults: { _controller: HSYSMainBundle:Donacion:receptorReceptor }

alta_donacion_receptor_formulario:
   pattern: /donacion/receptor/formulario/{don}/{rec}
   defaults: {_controller: HSYSMainBundle:Donacion:receptorFormulario }
  
alta_donacion_receptor_confirmar:
  pattern: /donacion/receptor/confirmar
  defaults: { _controller: HSYSMainBundle:Donacion:receptorConfirmar }

alta_donacion_autodonacion:
  pattern: /donacion/autodonacion
  defaults: { _controller: HSYSMainBundle:Donacion:autodonacion }

alta_donacion_autodonacion_donante:
  pattern: /donacion/autodonacion/donante
  defaults: { _controller: HSYSMainBundle:Donacion:autodonacionDonante }

confirmacion_donacion:
  pattern: /donacion/confirmacion
  defaults: { _controller: HSYSMainBundle:Donacion:confirmacion }
  
ver_donacion:
  pattern: /donacion/ver/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:ver }
  
ver_donacion_donante:
  pattern: /donacion/donante/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:verDonante }
  
modificar_donacion:
  pattern: /donacion/modificar/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:modificar }
  
anular_donacion:
  pattern: /donacion/anular/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:anular }
 
#SANGRE
pagina_sangre:
  pattern: /sangre
  defaults: { _controller: HSYSMainBundle:Sangre:index }

buscar_unidad_id:
  pattern: /sangre/buscarid
  defaults: { _controller: HSYSMainBundle:Sangre:buscarid }

buscar_unidad_tipohemocomponente:
  pattern: /sangre/buscartipohemocomponente
  defaults: { _controller: HSYSMainBundle:Sangre:buscarTipoHemocomponente }

buscar_unidad_estado:
  pattern: /sangre/buscarestado
  defaults: { _controller: HSYSMainBundle:Sangre:buscarEstado }

buscar_unidad_fecha:
  pattern: /sangre/buscarfecha
  defaults: { _controller: HSYSMainBundle:Sangre:buscarfecha }

buscar_unidad_donacion:
  pattern: /sangre/buscardonacion
  defaults: { _controller: HSYSMainBundle:Sangre:buscardonacion }

buscar_unidad_factorsanguineo:
  pattern: /sangre/buscarfactorsanguineo
  defaults: { _controller: HSYSMainBundle:Sangre:buscarfactorsanguineo }

buscar_unidad_avanzada:
  pattern: /sangre/buscaravanzada
  defaults: { _controller: HSYSMainBundle:Sangre:buscaravanzada }

ver_unidad:
  pattern: /sangre/ver/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:ver}

modificarestado_unidad:
  pattern: /sangre/modificarestado/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:modificarestado}

desbloquear_unidad:
  pattern: /sangre/desbloquear/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:desbloquear }
  
transfundir_unidad:
  pattern: /sangre/transfundir/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:transfundir }

desechar_unidad:
  pattern: /sangre/desechar/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:desechar }

bloquear_unidad:
  pattern: /sangre/bloquear/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:bloquear }

crearfraccionamiento_unidad:
  pattern: /sangre/crearfraccionamiento/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:crearfraccionamiento}

confirmacionfracionamiento_unidad:
  pattern: /sangre/confirmacionfraccionamiento/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:confirmacionfracionamiento}

imprimiretiqueta:
  pattern: /sangre/imprimiretiqueta/{id}
  defaults: { _controller: HSYSMainBundle:Sangre:imprimiretiqueta}

#ANALISIS
pagina_analisis:
  pattern: /analisis
  defaults: { _controller: HSYSMainBundle:Analisis:index }

alta_analisis:
  pattern: /analisis/nuevo
  defaults: { _controller: HSYSMainBundle:Analisis:nuevo }
  
alta_analisis_donacion:
  pattern: /analisis/nuevo/buscarpordonacion
  defaults: { _controller: HSYSMainBundle:Analisis:nuevoDonacion }
  
alta_analisis_bolsa:
  pattern: /analisis/nuevo/buscarporbolsa
  defaults: { _controller: HSYSMainBundle:Analisis:nuevoBolsa }
  
alta_analisis_donante:
  pattern: /analisis/nuevo/buscarpordonante
  defaults: { _controller: HSYSMainBundle:Analisis:nuevoDonante }
  
alta_analisis_fecha:
  pattern: /analisis/nuevo/buscarporfecha
  defaults: { _controller: HSYSMainBundle:Analisis:nuevoFecha }

alta_analisis_form:
  pattern: /analisis/nuevo/formulario/{id}
  defaults: { _controller: HSYSMainBundle:Analisis:nuevoForm }
  
confirmacion_analisis:
  pattern: /analisis/confirmacion/{accion}/{id}
  defaults: { _controller: HSYSMainBundle:Analisis:confirmacion }

modificar_analisis:
  pattern: /analisis/modificar/{id}
  defaults: { _controller: HSYSMainBundle:Analisis:modificar }  
  
buscar_analisis:
  pattern: /analisis/buscar
  defaults: { _controller: HSYSMainBundle:Analisis:buscar }

ver_analisis:
  pattern: /analisis/ver/{id}
  defaults: { _controller: HSYSMainBundle:Analisis:ver }

#Informes
pagina_informes:
  pattern: /informes
  defaults: { _controller: HSYSMainBundle:Informes:index }

informe_analisis:
  pattern: /informes/analisis
  defaults: { _controller: HSYSMainBundle:Informes:informeanalisis }

informe_descarte:
  pattern: /informes/descarte
  defaults: { _controller: HSYSMainBundle:Informes:informedescarte }

informe_desbloqueo:
  pattern: /informes/desbloqueo
  defaults: { _controller: HSYSMainBundle:Informes:informedesbloqueo }

informe_voluntario:
  pattern: /informes/voluntario
  defaults: { _controller: HSYSMainBundle:Informes:informevoluntario }

informe_extraccion:
  pattern: /informes/extraccion
  defaults: { _controller: HSYSMainBundle:Informes:informeextraccion }

informe_vencimiento:
  pattern: /informes/vencimiento
  defaults: { _controller: HSYSMainBundle:Informes:informevencimiento }

informe_stock:
  pattern: /informes/stock
  defaults: { _controller: HSYSMainBundle:Informes:informestock }

#autocargado
autocargado:
  pattern: /autocargado
  defaults: { _controller: HSYSMainBundle:Cargador:carga }
