
hsys_main_homepage:
  pattern:  /
  defaults: { _controller: HSYSMainBundle:Inicio:index }

#DONANTES
pagina_donante:
  pattern: /donante
  defaults: { _controller: HSYSMainBundle:Donante:index }

alta_donante:
  pattern: /donante/nuevo
  defaults: { _controller: HSYSMainBundle:Donante:nuevo }

confirmacion:
  pattern: /donante/confirmacion
  defaults: { _controller: HSYSMainBundle:Donante:confirmacion }
    
modificar_donante:
  pattern: /donante/modificar/{id}
  defaults: { _controller: HSYSMainBundle:Donante:modificar }
  
excluir_donante:
  pattern: /donante/excluir/{id}
  defaults: { _controller: HSYSMainBundle:Donante:excluir }

buscar_donante:
  pattern: /donante/buscar
  defaults: { _controller: HSYSMainBundle:Donante:buscar }

#EXTRACCIONES/DONACION
pagina_donacion:
  pattern: /donacion
  defaults: { _controller: HSYSMainBundle:Donacion:index }  
  
alta_donacion:
  pattern: /donacion/nueva
  defaults: { _controller: HSYSMainBundle:Donacion:nuevo }
  
confirmacion_donacion:
  pattern: /donacion/confirmacion
  defaults: { _controller: HSYSMainBundle:Donacion:confirmacion }
  
#SANGRE
pagina_sangre:
  pattern: /sangre
  defaults: { _controller: HSYSMainBundle:Sangre:index }

#ANALISIS
pagina_analisis:
  pattern: /analisis
  defaults: { _controller: HSYSMainBundle:Analisis:index }

alta_analisis:
  pattern: /analisis/nuevo
  defaults: { _controller: HSYSMainBundle:Analisis:nuevo }
  
confirmacion_analisis:
  pattern: /analisis/confirmacion
  defaults: { _controller: HSYSMainBundle:Analisis:confirmacion }

#autocargado
autocargado:
  pattern: /autocargado
  defaults: { _controller: HSYSMainBundle:Cargador:carga }
