hsys_main_homepage:
  pattern:  /
  defaults: { _controller: HSYSMainBundle:Inicio:index }

#DONANTES
pagina_donante:
  pattern: /donante
  defaults: { _controller: HSYSMainBundle:Donante:index }

alta_donante:
  pattern: /donante/nuevo
  defaults: { _controller: HSYSMainBundle:Donante:nuevo }

confirmacion:
  pattern: /donante/confirmacion/{accion}/{id}
  defaults: { _controller: HSYSMainBundle:Donante:confirmacion }
    
modificar_donante:
  pattern: /donante/modificar/{id}
  defaults: { _controller: HSYSMainBundle:Donante:modificar }
  
excluir_donante:
  pattern: /donante/excluir/{id}
  defaults: { _controller: HSYSMainBundle:Donante:excluir }

buscar_donante:
  pattern: /donante/buscar
  defaults: { _controller: HSYSMainBundle:Donante:buscar }

ver_donante:
  pattern: /donante/ver/{id}
  defaults: { _controller: HSYSMainBundle:Donante:ver }

habilitar_donante:
  pattern: /donante/habilitar/{id}
  defaults: { _controller: HSYSMainBundle:Donante:habilitar }

#EXTRACCIONES/DONACION
pagina_donacion:
  pattern: /donacion
  defaults: { _controller: HSYSMainBundle:Donacion:index }  
  
buscar_donacion_numero:
  pattern: /donacion/buscarpornumero
  defaults: { _controller: HSYSMainBundle:Donacion:buscarNumero }
  
buscar_donacion_donante:
  pattern: /donacion/buscarpordonante
  defaults: { _controller: HSYSMainBundle:Donacion:buscarDonante }
  
buscar_donacion_fecha:
  pattern: /donacion/buscarporfecha
  defaults: { _controller: HSYSMainBundle:Donacion:buscarFecha }
  
alta_donacion:
  pattern: /donacion/nueva
  defaults: { _controller: HSYSMainBundle:Donacion:nuevo }

alta_donacion_voluntaria:
  pattern: /donacion/voluntaria
  defaults: { _controller: HSYSMainBundle:Donacion:voluntaria }
  
alta_donacion_voluntaria_donante:
  pattern: /donacion/voluntaria/donante
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaDonante }

alta_donacion_voluntaria_formulario:
  pattern: /donacion/voluntaria/formulario/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaFormulario }

alta_donacion_voluntaria_confirmar:
  pattern: /donacion/voluntaria/confirmar
  defaults: { _controller: HSYSMainBundle:Donacion:voluntariaConfirmar }

alta_donacion_receptor:
  pattern: /donacion/receptor
  defaults: { _controller: HSYSMainBundle:Donacion:receptor }
  
alta_donacion_receptor_donante:
  pattern: /donacion/receptor/donante
  defaults: { _controller: HSYSMainBundle:Donacion:receptorDonante }
  
alta_donacion_receptor_receptor:
  pattern: /donacion/receptor/{don}/receptor
  defaults: { _controller: HSYSMainBundle:Donacion:receptorReceptor }

alta_donacion_receptor_formulario:
   pattern: /donacion/receptor/formulario/{don}/{rec}
   defaults: {_controller: HSYSMainBundle:Donacion:receptorFormulario }
  
alta_donacion_receptor_confirmar:
  pattern: /donacion/receptor/confirmar
  defaults: { _controller: HSYSMainBundle:Donacion:receptorConfirmar }

confirmacion_donacion:
  pattern: /donacion/confirmacion
  defaults: { _controller: HSYSMainBundle:Donacion:confirmacion }
  
ver_donacion:
  pattern: /donacion/ver/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:ver }
  
modificar_donacion:
  pattern: /donacion/modificar/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:modificar }
  
anular_donacion:
  pattern: /donacion/anular/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:anular }

exclusion_donacion:
  pattern: /donacion/exclusion/{id}
  defaults: { _controller: HSYSMainBundle:Donacion:exclusion }
 
#SANGRE
pagina_sangre:
  pattern: /sangre
  defaults: { _controller: HSYSMainBundle:Sangre:index }

#ANALISIS
pagina_analisis:
  pattern: /analisis
  defaults: { _controller: HSYSMainBundle:Analisis:index }

alta_analisis:
  pattern: /analisis/nuevo
  defaults: { _controller: HSYSMainBundle:Analisis:nuevo }
  
confirmacion_analisis:
  pattern: /analisis/confirmacion
  defaults: { _controller: HSYSMainBundle:Analisis:confirmacion }
  
modificar_analisis:
  pattern: /analisis/modificar/{id}
  defaults: { _controller: HSYSMainBundle:Analisis:modificar }  
  
buscar_analisis:
  pattern: /analisis/buscar
  defaults: { _controller: HSYSMainBundle:Analisis:buscar }

#autocargado
autocargado:
  pattern: /autocargado
  defaults: { _controller: HSYSMainBundle:Cargador:carga }
