parameters:
#    hsys_main.example.class: HSYS\MainBundle\Example

services:
#    hsys_main.example:
#        class: %hsys_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
