parameters:
    database_driver: pdo_sqlsrv
    database_host: German-U\SQLEXPRESS
    database_port: null
    database_name: hsys
    database_user: hsysuser
    database_password: '123456'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8ecfe63c7e488e48c8bad710c6eef8c27
    database_path: null
