security:
 encoders: 
  HSYS\MainBundle\Entity\Usuario:
   algorithm: sha512
   encode-as-base64: true	
   iterations: 10
 providers:
  user_db:
   entity: { class: HSYS\MainBundle\Entity\Usuario, property:username }
 firewalls:
  dev:
   pattern: ^/(_(profiler|wdt)|css|images|js)/
   security: false
  login:
   pattern: /login$
   security: false
  secured_area:
   pattern: ^/
   anonymous: ~
  # http_basic:
    #realm: "Introduzca Usuario y Contrasena"
   form_login:
    login_path: /login
    check_path: /login_check
   logout:
    path: /logout
    target: /
 role_hierarchy:
  ROLE_ADMIN: [ROLE_BIOQUIMICO,ROLE_MEDICO,ROLE_PERSONAL]
  ROLE_MEDICO: [ROLE_PERSONAL]
        
         
#  - { path: ^/admin, roles: ROLE_ADMIN}
                 
